@host = http://localhost:3000
@studyId = b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
@habitId = fb4bf2a8-1f91-44c0-91e6-90527a0af427

// 주간 체크 조회 (현재 주 KST)
GET {{host}}/habitChecks/{{studyId}}/{{habitId}}/habitCheck/weekly
Accept: application/json

###

// 오늘 체크 토글 (없으면 생성하며 true로 설정)
POST {{host}}/habitChecks/{{studyId}}/{{habitId}}/habitCheck/toggle
Accept: application/json
Content-Type: application/json

{}

###

GET {{host}}/health
Accept: application/json
