// 오늘의 습관 조회
GET http://localhost:3000/habits

###

GET http://localhost:3000/habits/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e/today?password=1234

###

// 오늘의 습관 생성
POST http://localhost:3000/habits/create/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
Content-Type: application/json

{
  "name": "도파민 디톡스"
}

###

POST http://localhost:3000/habits/create/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
Content-Type: application/json

{
  "name": "매일 산책하기"
}

###

PATCH  http://localhost:3000/habits/delete/fb4bf2a8-1f91-44c0-91e6-90527a0af427

