@host = http://localhost:3000
@studyId = 6cdf52a3-202c-4c13-bcd3-147174b25d8e

### Get studies (list) - supports offset, limit, order=newest|oldest
GET {{host}}/studies?offset=0&limit=5&order=newest

### Get one study by id
# Note: route in code is defined as '/study/:id' (with a slash)
GET {{host}}/studies/{{studyId}}

### Create a study (POST /study)
POST {{host}}/studies
Content-Type: application/json

{
	"nickName": "tester",
	"studyName": "HTTP Test Study",
	"description": "샘플 설명입니다.",
	"backgroundImg": "green",
	"password": "secret-password"
}

### Patch (update) a study
PATCH {{host}}/studies/{{studyId}}
Content-Type: application/json

{
	"studyName": "Updated Study Name",
	"description": "업데이트된 설명"
}

### Delete a study
DELETE {{host}}/studies/{{studyId}}

